FROM mcr.microsoft.com/devcontainers/python:1-3.10-bookworm

# 작업 디렉토리 설정
WORKDIR /workspaces/jupyterlab-extension

# 필요 패키지 설치
# python >=3.10,<3.11.0a0
# jupyterlab >=4.0.0,<5
# nodejs >=18,<19
# pip
# wheel
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt update && \
    apt install -y nodejs
RUN pip install --upgrade pip
RUN pip install build
RUN pip install 'jupyterlab>=4.4.0,<5'
RUN pip install 'copier~=9.2' jinja2-time
RUN pip install requests
